World wide web

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,22 +1,36 @@
 #!/usr/bin/env bash
 #Bash script that will display information about subdomains.
-subdomains=( "www" "lb-01" "web-01" "web-02" )
+# Function to query DNS records and display information
+query_dns() {
+    local domain="$1"
+    local subdomain="$2"
 
-runDig () {
-    subdomain=$1
-    domain=$2
+    if [ -z "$subdomain" ]; then
+        subdomains=("www" "lb-01" "web-01" "web-02")
+    else
+        subdomains=("$subdomain")
+    fi
 
-    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
+    for sub in "${subdomains[@]}"; do
+        dns_result=$(dig +short -t A "$sub.$domain")
+        if [ -z "$dns_result" ]; then
+            echo "The subdomain $sub is not found."
+        else
+            record_type=$(dig +short -t A "$sub.$domain" | awk 'NF > 0 { print "A record" }')
+            destination=$(dig +short -t A "$sub.$domain")
+            echo "The subdomain $sub is a $record_type and points to $destination"
+        fi
+    done
 }
 
-if [ $# -eq 1 ]; then
-    domain="$1"
-    for s in "${subdomains[@]}"
-    do
-	runDig "$s" "$domain"
-    done
-elif [ $# -eq 2 ]; then
-    domain="$1"
-    subdomain="$2"
-    runDig "$subdomain" "$domain"
+# Check for the correct number of arguments
+if [ "$#" -lt 1 ]; then
+    echo "Usage: $0 <domain> [subdomain]"
+    exit 1
 fi
+
+domain="$1"
+subdomain="$2"
+
+# Call the query_dns function
+query_dns "$domain" "$subdomain"
